services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: openpulse
      POSTGRES_PASSWORD: openpulse
      POSTGRES_DB: openpulse
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:4.0.1-rc2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  db_data:
